### ISSUE TITLE
Getting Started Resources?

### ISSUE THREAD

**Issue by rwaldron** [dimircea/iotduino#1]
Hello! Are there any "Getting Started" resources you'd recommend? The information the pcDuino site seems very scattered and even the book (pcDuino3) skips the basics of getting an sd card set up. Is that even necessary?

**Comment by dimircea** [comment]
Happy New Year!
Unfortunately there are very few resources for this really nice board. Here is an article I wrote on codeproject: "http://www.codeproject.com/Articles/852169/iotduino-takes-JavaScript-to-the-land-of-microseco" about using the PCDuino with Node.js. And here: "http://www.linksprite.com/?page_id=874" you can find also a set of resources for the PCDuino board.

No, it is not necessarily to use a card, but the built-in flash is a bit too slow. With a good Micro-SD card (e.g. class 10) you can have your board making things using the storage much faster (e.g. booting is about 2-3 times faster). 

Have fun!
